"""empty message

Revision ID: 19d9d14bfdb7
Revises: f3fa5135e2d8
Create Date: 2022-10-19 16:44:54.889950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19d9d14bfdb7'
down_revision = 'f3fa5135e2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'id_planets',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'id_characters',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'id_characters',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'id_planets',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
