"""empty message

Revision ID: d8b4ded47ef2
Revises: 8b348cb5fa6c
Create Date: 2022-10-18 18:14:23.162628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8b4ded47ef2'
down_revision = '8b348cb5fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('lastName', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('userName', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['userName'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'userName')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
