"""empty message

Revision ID: ea2183c40c85
Revises: ad952363bbda
Create Date: 2022-10-18 18:56:47.531362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea2183c40c85'
down_revision = 'ad952363bbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('lastName', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('name', sa.String(length=250), nullable=False))
    op.drop_column('planets', 'nombre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('nombre', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('planets', 'name')
    op.drop_column('characters', 'lastName')
    # ### end Alembic commands ###
